/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package apk.perawatankendaraan;

import javax.swing.*;
import java.awt.*;
import java.util.Locale;
import java.util.ResourceBundle;
/**
 *
 * @author MyLaptop
 */
public class MainFrame extends javax.swing.JFrame {
    private ResourceBundle bundle;
    private JTabbedPane tabbedPane;
    private JMenuBar menuBar;
    private JMenu languageMenu;
    /**
     * Creates new form MainFrame
     */
    public MainFrame() {
        setLanguage(new Locale("id", "ID"));
        
        initComponents();
        setupUI();
        setTitle(bundle.getString("app.title"));
        setSize(900, 600);
        setLocationRelativeTo(null);
        setDefaultCloseOperation(JFrame.EXIT_ON_CLOSE);
    }

     private void setupUI() {
        menuBar = new JMenuBar();
        languageMenu = new JMenu(bundle.getString("menu.language"));
        
        JMenuItem indonesianItem = new JMenuItem("Bahasa Indonesia");
        indonesianItem.addActionListener(e -> setLanguage(new Locale("id", "ID")));
        
        JMenuItem englishItem = new JMenuItem("English");
        englishItem.addActionListener(e -> setLanguage(new Locale("en", "US")));
        
        languageMenu.add(indonesianItem);
        languageMenu.add(englishItem);
        menuBar.add(languageMenu);
        setJMenuBar(menuBar);
        tabbedPane = new JTabbedPane();
        tabbedPane.addTab(bundle.getString("tab.vehicles"), new VehiclePanel(bundle));
        tabbedPane.addTab(bundle.getString("tab.service"), new ServicePanel(bundle));
        
        add(tabbedPane);
    }
     
     public void setLanguage(Locale locale) {
        bundle = ResourceBundle.getBundle("apk.perawatankendaraan.resources.LanguageBundle", locale);
        updateUITexts();
    }
     
     private void updateUITexts() {
        setTitle(bundle.getString("app.title"));
        languageMenu.setText(bundle.getString("menu.language"));
        
        tabbedPane.setTitleAt(0, bundle.getString("tab.vehicles"));
        tabbedPane.setTitleAt(1, bundle.getString("tab.service"));
        tabbedPane.setTitleAt(2, bundle.getString("tab.backup"));
        
        // Update semua komponen UI
        SwingUtilities.updateComponentTreeUI(this);
    }
    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 400, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 300, Short.MAX_VALUE)
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(MainFrame.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(MainFrame.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(MainFrame.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(MainFrame.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new MainFrame().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    // End of variables declaration//GEN-END:variables
}
