/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package apk.perawatankendaraan;

import javax.swing.*;
import java.awt.*;
import java.util.ResourceBundle;
/**
 *
 * @author MyLaptop
 */
public class VehiclePanel extends javax.swing.JFrame {
    private ResourceBundle bundle;
    private JTable vehicleTable;
    private JButton addButton, editButton, deleteButton;
    /**
     * Creates new form VehiclePanel
     */
    public VehiclePanel(ResourceBundle bundle) {
        this.bundle = bundle;
        initComponents();
        setupUI();
    }

    private void setupUI() {
        setLayout(new BorderLayout());
        
        // Toolbar
        JToolBar toolBar = new JToolBar();
        addButton = new JButton(bundle.getString("button.add"));
        editButton = new JButton(bundle.getString("button.edit"));
        deleteButton = new JButton(bundle.getString("button.delete"));
        
        addButton.addActionListener(e -> addVehicle());
        editButton.addActionListener(e -> editVehicle());
        deleteButton.addActionListener(e -> deleteVehicle());
        
        toolBar.add(addButton);
        toolBar.add(editButton);
        toolBar.add(deleteButton);
        add(toolBar, BorderLayout.NORTH);
        String[] columnNames = {
            bundle.getString("table.plate"),
            bundle.getString("table.type"),
            bundle.getString("table.brand"),
            bundle.getString("table.model"),
            bundle.getString("table.year"),
            bundle.getString("table.next_service")
        };
        
        Object[][] data = {
            {"B 1234 ABC", "Mobil", "Toyota", "Avanza", 2020, "15/09/2023"},
            {"F 5678 XYZ", "Motor", "Honda", "Beat", 2021, "20/10/2023"}
        };
        
        vehicleTable = new JTable(data, columnNames);
        add(new JScrollPane(vehicleTable), BorderLayout.CENTER);
    }
    
    public void updateLanguage(ResourceBundle newBundle) {
        this.bundle = newBundle;
        
        // Update tombol
        addButton.setText(bundle.getString("button.add"));
        editButton.setText(bundle.getString("button.edit"));
        deleteButton.setText(bundle.getString("button.delete"));
        String[] columnNames = {
            bundle.getString("table.plate"),
            bundle.getString("table.type"),
            bundle.getString("table.brand"),
            bundle.getString("table.model"),
            bundle.getString("table.year"),
            bundle.getString("table.next_service")
        };
        
        for (int i = 0; i < columnNames.length; i++) {
            vehicleTable.getColumnModel().getColumn(i).setHeaderValue(columnNames[i]);
        }
        vehicleTable.getTableHeader().repaint();
    }
    private void addVehicle() {
        // Implementasi untuk menambahkan kendaraan
        JOptionPane.showMessageDialog(this, "Fungsi untuk menambahkan kendaraan belum diimplementasikan.");
    }
    private void editVehicle() {
        // Implementasi untuk mengedit kendaraan
        JOptionPane.showMessageDialog(this, "Fungsi untuk mengedit kendaraan belum diimplementasikan.");
    }
    private void deleteVehicle() {
        // Implementasi untuk menghapus kendaraan
        JOptionPane.showMessageDialog(this, "Fungsi untuk menghapus kendaraan belum diimplementasikan.");
    }
    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 400, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 300, Short.MAX_VALUE)
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(VehiclePanel.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(VehiclePanel.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(VehiclePanel.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(VehiclePanel.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>
         try {
            for (UIManager.LookAndFeelInfo info : UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (Exception ex) {
            java.util.logging.Logger.getLogger(VehiclePanel.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(() -> {
            // Menggunakan ResourceBundle default untuk contoh
            ResourceBundle bundle = ResourceBundle.getBundle("apk.perawatankendaraan.resources.LanguageBundle", new Locale("id", "ID"));
            new VehiclePanel(bundle).setVisible(true);
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    // End of variables declaration//GEN-END:variables
}
